version: '3'
services:

  postgres:
    image: postgres:10-alpine
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d grafana -U grafana"]
      timeout: 5s
      retries: 10
    networks:
      - default

  superset:
    image: tylerfowler/superset:latest
    hostname: superset
    container_name: superset
    ports:
      - 8088:8088
      - 5555:5555
    depends_on:
      - postgres
    environment:
      ADMIN_USERNAME: admin
      ADMIN_FIRST_NAME: admin
      ADMIN_LAST_NAME: admin
      ADMIN_EMAIL: nobody@nowhere.com
      ADMIN_PWD: changeme
    networks:
      - default

volumes:
  postgres-data:
